FROM alpine

RUN apk -U --no-cache add \
  python3 \
  py3-pip

# RUN pip3 install --upgrade pip && \
    # pip3 install --no-cache-dir \
    # tornado \
    # jinja2 \
    # mako

RUN apk add --no-cache py3-tornado py3-jinja2 py3-mako